# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4ff77b215bc68dbf36542cd327778717b4c817a88b6cfa7da0cee75898b0b03dd02e5cfeb76df485e26ebbe1f238e6ac65ec8b7ff47294cc379784b51e00608

test:
  secret_key_base: a68e236c9a32c2ff878eb7d43c2b8b331463fa546a9ce25fb413339f9a8ca61d395c38e1dc0a99afdbe5c433266f04ba68b6a63a399e4e6fe73999e4d143a94f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
